[package]
name = "smictl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4.4.0", features = ["derive"] }
redis = { version = "0.25", features = ["tokio-comp"] }
rustyline = "13"
tokio = { version = "1", features = ["full"] }
